### PR TITLE
fix build errors

### PR DESCRIPTION
**Pull request by danielk117**

### CODE REVIEW

**Comment by danielk117** [comment]
sorry, this belongs to my master master branch 😉

**Comment by duhow** [comment]
no problem, but actually I will add your commits as well and try it out 🙂 
feel free to push for any improvements! 💪🏻

**Comment by danielk117** [comment]
of course 🙂

BTW, I got an build error for blue-alsa package with your latest updates. thats why I removed the flags `--enable-aptx --enable-aptx-hd` for blue-alsa and build is successful now. https://github.com/duhow/xiaoai-patch/pull/62/files#diff-65ee44e09ce70af0debdfdfa34d0605a91e35ee4970e50dd67888d5aa1fa0c44

any idea how to fix this?

**Comment by duhow** [comment]
`blue-alsa` uses `lastest` from **master**, so very likely there's a recent change that may be breaking.
https://github.com/arkq/bluez-alsa
I'll have a look and post a patch if needed.

**Comment by duhow** [comment]
Assuming this is the issue: https://github.com/arkq/bluez-alsa/commit/c0378e54c459439000d828b4a0c7669586b2dc21

**Comment by danielk117** [comment]
ah nice, you already fixed it 👍

**Pull request closed without merging**
