### PR TITLE
Add Squeezelite and Opusfile packages

### LINKED ISSUE #8: Requirements for new packages
Since I ordered a couple more smart speakers for around the house, it was time for me to look at the multiroom audio solution again. Currently I'm using snapcast for two speakers and while the sync is fantastic, the usability and compatibility with home assistant and automations leaves a lot to desire imho. I want to test out Logitech media server again. The sync is not as perfect as snapcast, but it is way easier to handle I think. 

For that, I would need to build the squeezelite package into the image of course and if I'm doing that, it would make sense to provide the package.mk file to this project. Dependency wise it seems we're only missing libsoxr, everything else is already there judging from the [AUR package from arch]( https://aur.archlinux.org/packages/squeezelite/) 

I would probably use the snapcast package as a template and modify it for the squeezelite packages. I haven't looked at the contents for libsoxr yet, but one the other lib* packages should be provide a template as well. 

Any requirements from your side for the do's and don'ts of a new package? Could be a good exercise for any additional packages that might come in the future.

### PR DESCRIPTION
**Pull request by duhow**
Closes #8

### CODE REVIEW

**Comment by duhow** [comment]
@hillbicks try the package and let me know if that works for you. You have to edit `packages.sh` to include building it.

**Comment by hillbicks** [comment]
Yes, it builds fine, squeezelite is running as a service on the LX06 now! Thanks for that!

We need to add conf file for squeezelite though. I took the snapcast init setup and modified it for squeezelite, otherwise I wouldn't have been able to connect to the server (different subnet). If we do that, I suggest moving the name part into the config as well.

**Comment by hillbicks** [comment]
Here is the change I made to squeezelite.init

```
CONF=/data/squeezelite/squeezelite.conf
PROG=/usr/bin/squeezelite

make_cmdline() {
        cmdline=""

        # name

        model_name=$(uci -c /usr/share/mico get version.version.HARDWARE)
        cmdline="$cmdline -M $model_name"
        if [ -f "$CONF" ]; then
          source ${CONF}
          [ -n "${NAME}" ] &&  cmdline="$cmdline -n ${NAME}"
          [ -n "${HOST}" ] &&  cmdline="$cmdline -s ${HOST}"

        fi
}
```

**Comment by duhow** [comment]
Looks like there's no standard configuration defined, so I took the one based on the Debian package and applied it.

**Pull request merged**
