### PR TITLE
Fix shairport-sync configuration

### PR DESCRIPTION
**Pull request by firedevel**

### CODE REVIEW

**Comment by firedevel** [comment]
```
//	airplay_device_id_offset = 0; // (AirPlay 2 only) add this to the default airplay_device_id calculated from one of the device's MAC address
//	airplay_device_id = 0x<six-digit_hexadecimal_number>L; // (AirPlay 2 only) use this as the airplay_device_id e.g. 0xDCA632D4E8F3L -- remember the "L" at the end as it's a 64-bit quantity!
```
`airplay_device_id` is set by deafult, adding this will cause a problem.

**Comment by duhow** [comment]
This was added on purpose to mitigate future issues with different MAC address appearing, as this would create multiple, different AirPlay devices, each time the speaker reboots.

https://github.com/duhow/xiaoai-patch/blob/2cfe46089131ed03f901b628f96262de8822c3c5/packages/shairport-sync/config/shairport.init#L20-L21

Can you provide details in what device and firmware base version are you having issues?

**Comment by firedevel** [comment]
LX01
rootfs: 1.32.6
kernel: 3.4.39 from 1.32.6

```
/# uname -a
Linux LX01-2982 3.4.39 #1 SMP PREEMPT Tue Nov 28 14:33:17 UTC 2023 armv7l GNU/Linux
```

```
/# shairport-sync 
fatal error: Line 3 of the configuration file "/etc/shairport-sync.conf":
syntax error
```

```
/# cat /etc/shairport-sync.conf
general =
{
  airplay_device_id = 0x%MAC%L;
  run_this_when_volume_is_set = "/bin/volume color -q";
  dbus_service_bus = "system";
};
...
```

I guess this is because `/etc` is read-only and I think that `airplay_device_id` is calculated using the MAC address by default, and this configuration is not needed.

**Comment by duhow** [comment]
Gotcha, then the issue is expected and I'm working on a fix.

Basically, LX01 old version `1.32.6` does not have `micocfg_mac`, command returns error, and config is not properly rendered, which causes this problem.

I'm working to upgrade to latest version available for LX01 `1.62.6` which does include this, but meanwhile I can hotfix this for the time being.

**Comment by duhow** [comment]
PS: you can fix this entry locally in the copied file to `/data/shairport-sync.conf` .

**Comment by duhow** [comment]
Fixed in 45b49ea9640d74ab90467817b3d0a1d3cd2abe0e .

**Pull request closed without merging**
